USE [master]
GO
/****** Object:  Database [ADMINISTRACION_ESCOLAR]    Script Date: 3/11/2025 1:00:08 PM ******/
CREATE DATABASE [ADMINISTRACION_ESCOLAR]
GO

USE [ADMINISTRACION_ESCOLAR]
GO
/****** Object:  Table [dbo].[ESTUDIANTE]    Script Date: 3/11/2025 1:00:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESTUDIANTE](
	[CODIGO] [nvarchar](8) NOT NULL,
	[NOMBRES] [nvarchar](100) NOT NULL,
	[APELLIDOS] [nvarchar](100) NOT NULL,
	[FECHA_NACIMIENTO] [datetime] NOT NULL,
	[EDAD] [int] NOT NULL,
	[CORREO] [nvarchar](100) NOT NULL,
	[ESTADO] [nvarchar](1) NOT NULL,
	[USU_CREA] [nvarchar](100) NOT NULL,
	[FEC_CREA] [datetime] NOT NULL,
	[USU_MOD] [nvarchar](100) NULL,
	[FEC_MOD] [datetime] NULL,
	[USU_BLO] [nvarchar](100) NULL,
	[FEC_BLO] [datetime] NULL,
 CONSTRAINT [PK_ESTUDIANTE] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ESTUDIANTE_MATERIA]    Script Date: 3/11/2025 1:00:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESTUDIANTE_MATERIA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_ESTUDIANTE] [nvarchar](8) NOT NULL,
	[CODIGO_MATERIA] [nvarchar](8) NOT NULL,
	[ESTADO] [nvarchar](1) NOT NULL,
	[USU_CREA] [nvarchar](100) NOT NULL,
	[FEC_CREA] [datetime] NOT NULL,
	[USU_MOD] [nvarchar](100) NULL,
	[FEC_MOD] [datetime] NULL,
	[USU_BLO] [nvarchar](100) NULL,
	[FEC_BLO] [datetime] NULL,
 CONSTRAINT [PK_ESTUDIANTE_MATERIA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MATERIA]    Script Date: 3/11/2025 1:00:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MATERIA](
	[CODIGO] [nvarchar](8) NOT NULL,
	[NOMBRE] [nvarchar](100) NOT NULL,
	[INSTRUCTOR] [nvarchar](100) NOT NULL,
	[HORA_INICIO] [nvarchar](10) NOT NULL,
	[HORA_FIN] [nvarchar](10) NOT NULL,
	[UBICACION] [nvarchar](100) NOT NULL,
	[ESTADO] [nvarchar](1) NOT NULL,
	[USU_CREA] [nvarchar](100) NOT NULL,
	[FEC_CREA] [datetime] NOT NULL,
	[USU_MOD] [nvarchar](100) NULL,
	[FEC_MOD] [datetime] NULL,
	[USU_BLO] [nvarchar](100) NULL,
	[FEC_BLO] [datetime] NULL,
 CONSTRAINT [PK_MATERIA] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESTUDIANTE_MATERIA]  WITH CHECK ADD  CONSTRAINT [FK_EST_MAT_ESTUDIANTE] FOREIGN KEY([CODIGO_ESTUDIANTE])
REFERENCES [dbo].[ESTUDIANTE] ([CODIGO])
GO
ALTER TABLE [dbo].[ESTUDIANTE_MATERIA] CHECK CONSTRAINT [FK_EST_MAT_ESTUDIANTE]
GO
ALTER TABLE [dbo].[ESTUDIANTE_MATERIA]  WITH CHECK ADD  CONSTRAINT [FK_EST_MAT_MATERIA] FOREIGN KEY([CODIGO_MATERIA])
REFERENCES [dbo].[MATERIA] ([CODIGO])
GO
ALTER TABLE [dbo].[ESTUDIANTE_MATERIA] CHECK CONSTRAINT [FK_EST_MAT_MATERIA]
GO
USE [master]
GO
ALTER DATABASE [ADMINISTRACION_ESCOLAR] SET  READ_WRITE 
GO
